# Welcome to Plus!
#
# This config file affects your whole blog.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title:              Dani Polo
description:        Technical SEO at Scale and advanced optimization strategies.
url:                https://xscru.com # Site base hostname & protocol, e.g. http://example.com
baseurl:            "" # Site subpath, e.g. /blog
logo_image:
  dark:             logo-dark.png # Dark logo e.g logo-dark.svg upload to /uploads/ folder, used in header, mobile navigation and page sidebar About widget
  light:            logo-light.png # Light logo e.g. logo-light.svg upload to /uploads/ folder, used in footer About widget
permalink:          /:title/ # Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
date_format:        "%B %-d, %Y" # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
uploads:            /uploads/ # Path to post content assets directory i.e post images, pdfs etc
paginate:           7 # Number of posts displayed on blog page
paginate_path:      "/blog/:num/" # Blog path
google_tag_manager: GTM-PXF3KSD  # Google Tag Manager Container
ampdir:             amp
disqus:
  shortname:        xscru

instagram_accesstoken: 

footer:             # Default footer image settings
  copyright:        xscrü © 2019

# navbar settings
navbar_primary:
  sticky:           true
  social:           true
  search:           true

# Social share buttons
social_share:
  twitter:          true
  facebook:         true
  linkedin:         true
  pinterest:        false
  reddit:           true

# Social networks
social_networks:
  email:          
  website:        
  facebook:
  flickr:         
  dribbble:       
  github:           https://github.com/danipolo
  reddit:         
  instagram:       
  linkedin:         https://www.linkedin.com/in/polodaniel/
  pinterest:      
  twitter:          https://twitter.com/danipoloflorit
  vimeo:          
  youtube:    

# Strings
strings:
  author_by:        By

# Build settings
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-sitemap
  - amp-jekyll

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - netlify.toml
  - package.json
  - CHANGELOG
  - LICENSE
  - README
  - /docs
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  style:            compressed


# collections:
collections:
  authors:
    output: true
  category:
    output: true

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      sidebar: left
  # _authors
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  # _category
  - scope:
      path: ""
      type: category
    values:
      layout: category
